Repository Techeer-Hogwarts/frontend, pull requests merged in 2024-11, with the labels that each got.

#18 design: 통합검색 페이지 퍼블리싱
  public/images/arrow-outline.svg
  src/app/search/page.tsx
  src/components/common/Dropdown.tsx
  src/components/project/Card.tsx
  src/components/search/BlogSection.tsx
  src/components/search/CardItem.tsx
  src/components/search/CategoryTab.tsx
  src/components/search/ProjectSection.tsx
  src/components/search/ResumeSection.tsx
  src/components/search/Section.tsx
  src/components/search/SessionSection.tsx
  src/stories/common/Dropdown.stories.tsx
  src/stories/common/InputField.stories.tsx
  src/stories/components/Dropdown.stories.tsx
  src/stories/components/InputField.stories.tsx
  src/stories/signup/ExperienceSection.stories.tsx
  src/stories/signup/PositionSelect.stories.tsx
Labels: ✨ FEAT

#19 test: 탭바, 프로필박스 스토리북
  src/app/detail/page.tsx
  src/components/common/SearchBar.tsx
  src/components/profile/ProfileBox.tsx
  src/stories/components/ProfileBox.stories.tsx
  src/stories/components/TapBar.stories.tsx
Labels: ✅ TEST

#23 feat : 빌드 에러 수정
  src/app/changepassword/page.tsx
  src/app/detail/page.tsx
  src/app/login/page.tsx
  src/app/project/add/project/@modal/(.)addMember/page.tsx
  src/app/project/add/project/addMember/page.tsx
  src/app/project/add/study/@modal/(.)addMember/page.tsx
  src/app/project/detail/project/[id]/page.tsx
  src/app/resume/layout.tsx
  src/app/search/page.tsx
  src/components/calender/Calendar.tsx
  src/components/project/add/AddBtn.tsx
  src/components/project/add/AddMember.tsx
  src/components/project/add/AddRecruit.tsx
  src/components/project/add/project/AddResults.tsx
  src/components/project/add/study/AddGoal.tsx
  src/components/project/detail/Member.tsx
  src/components/project/modal/ProjectModal.tsx
  src/components/project/modal/StudyModal.tsx
  src/components/resume/OtherResume.tsx
  src/components/resume/ResumeFolder.tsx
  src/components/search/CategoryTab.tsx
  src/stories/Page.tsx
Labels: 🧹 CHORE

#21 design: 온보딩 페이지 퍼블리싱 완료
  public/bookmark.png
  public/clip_large.png
  public/clip_small.png
  public/halfcircle.png
  public/nametag.png
  public/resume.png
  public/sample1.png
  public/sample2.png
  public/sample3.png
  public/sample4.png
  public/sample5.png
  public/sample6.png
  public/test.png
  src/app/blog/page.tsx
  src/app/calendar/page.tsx
  src/app/page.tsx
  src/app/resume/page.tsx
  src/app/session/page.tsx
  src/components/common/NevBar.tsx
  src/components/onboarding/Banner.tsx
  src/components/onboarding/Firtst.tsx
  src/components/onboarding/Fourth.tsx
  src/components/onboarding/Last.tsx
  src/components/onboarding/Second.tsx
  src/components/onboarding/Stack.tsx
  src/components/onboarding/Techeer.tsx
  src/components/onboarding/Third.tsx
Labels: ✨ FEAT
