Repository Techeer-Hogwarts/frontend, pull requests merged in 2025-05, with the labels that each got.

#78 refact : 회원가입 페이지 리팩토링
  src/app/signup/page.tsx
  src/components/signup/BlogComponent.tsx
  src/constants/signupInfo.ts
  src/hooks/auth/useSignupForm.ts
  src/hooks/auth/useSignupHandler.ts
  src/types/signup/signup.type.ts
Labels: 🚀 REFACTOR

#79 fix, feat, design: 캘린더 관련 건의 사항 수정
  src/api/calendar/deleteEvent.ts
  src/api/calendar/getCurrentUser.ts
  src/api/calendar/patchEvent.ts
  src/api/calendar/postEvent.ts
  src/components/calender/Calendar.tsx
  src/components/calender/CalendarClient.tsx
  src/components/calender/CalendarEventCard.tsx
  src/components/calender/EventsDetailModal.tsx
  src/components/calender/FilterBtn.tsx
  src/constants/category.ts
Labels: ✨ FEAT, 🛠️ FIX

#80 refactor, fix : 세션 관련 리팩토링 및 세션 수정 누르면 ui 오류 수정
  src/api/session/session.ts
  src/app/session/_lib/deleteSession.ts
  src/app/session/_lib/getBestSessions.ts
  src/app/session/_lib/getSessions.ts
  src/app/session/_lib/getSingleSession.ts
  src/app/session/page.tsx
  src/components/blog/AddPostModal.tsx
  src/components/common/ModalInputField.tsx
  src/components/mypage/Bookmark.tsx
  src/components/mypage/Likes.tsx
  src/components/session/AddSessionModal.tsx
  src/components/session/CategoryBtn.tsx
  src/components/session/EditSession.tsx
  src/components/session/FilterBtn.tsx
  src/components/session/ModalManager.tsx
  src/components/session/SessionList.tsx
  src/components/session/SessionMenu.tsx
  src/components/session/SessionPost.tsx
  src/components/session/ShowVideo.tsx
  src/hooks/session/useSessionsQuery.ts
  src/store/useAuthModal.ts
  src/stories/components/ModalInputField.stories.tsx
  src/stories/session/SessionPost.stories.tsx
  src/types/ session/session.ts
Labels: 🛠️ FIX, 🚀 REFACTOR

#81 refactor: API 정리 및 경로 수정
  src/api/search/getSearch.ts
  src/api/search/search.ts
  src/components/common/NavBar.tsx
  src/components/common/SearchBar.tsx
  src/hooks/calendar/useCalendar.ts
Labels: 🚀 REFACTOR
