Repository Techeer-Hogwarts/frontend, pull requests merged in 2025-09, with the labels that each got.

#118 hotfix: 경력 타임존 수정
  src/api/mypage/deleteExperience.ts
  src/api/mypage/getProfileImg.ts
  src/api/mypage/updateProfile.ts
  src/components/mypage/Home.tsx
  src/components/mypage/MyExperienceSection.tsx
  src/components/mypage/Profile.tsx
  src/components/profile/ProfileBox.tsx
  src/components/signup/ExperienceItem.tsx
  src/types/mypage/mypage.types.ts
Labels: 🐛 BUG

#141 set: googletagmanager 세팅
  package.json
  src/app/(protected)/cs/[id]/page.tsx
  src/app/(protected)/profile/[userId]/page.tsx
  src/app/(protected)/project/detail/project/[id]/page.tsx
  src/app/(protected)/project/detail/project/edit/[id]/page.tsx
  src/app/(protected)/project/detail/study/[id]/page.tsx
  src/app/(protected)/project/detail/study/edit/[id]/page.tsx
  src/app/(protected)/resume/[resumeId]/page.tsx
  src/app/layout.tsx
  src/components/onboarding/Section1.tsx
  src/lib/GoogleAnalytics.tsx
  src/types/project/project.ts
  src/types/project/projectEdit.ts
  src/types/project/studyEdit.ts
  tsconfig.json
  yarn.lock
Labels: ⚙️ Setting

#149 refactor: 이벤트 API refactor
  src/api/calendar/apis.ts
  src/api/calendar/deleteEvent.ts
  src/api/calendar/getCurrentUser.ts
  src/api/calendar/getEvent.ts
  src/api/calendar/getEventList.ts
  src/api/calendar/mutations.ts
  src/api/calendar/patchEvent.ts
  src/api/calendar/postEvent.ts
  src/api/calendar/queries.ts
  src/components/calender/AddCalendarModal.tsx
  src/components/calender/Calendar.tsx
  src/components/calender/CalendarClient.tsx
  src/components/calender/EventDeleteModal.tsx
  src/hooks/calendar/useCalendar.ts
Labels: 🚀 REFACTOR
