Repository Techeer-Hogwarts/frontend, pull requests merged in 2025-02, with the labels that each got.

#28 feat: auth api 연동
  next.config.mjs
  package.json
  public/git.svg
  public/medium.svg
  public/tistory.svg
  public/velog.svg
  src/app/blog/page.tsx
  src/app/changepassword/page.tsx
  src/app/detail/[resumeId]/page.tsx
  src/app/login/page.tsx
  src/app/mypage/leave/page.tsx
  src/app/mypage/page.tsx
  src/app/profile/[userId]/page.tsx
  src/app/signup/page.tsx
  src/components/common/AuthModal.tsx
  src/components/common/CareerTag.tsx
  src/components/common/EmailVerification.tsx
  src/components/common/ExperienceBtn.tsx
  src/components/common/InputField.tsx
  src/components/common/NevBar.tsx
  src/components/common/PositionTag.tsx
  src/components/mypage/AddBtn.tsx
  src/components/mypage/Carousel.tsx
  src/components/mypage/Home.tsx
  src/components/mypage/MyCareerToggle.tsx
  src/components/mypage/MyExperienceSection.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileInputField.tsx
  src/components/mypage/Settings.tsx
  src/components/profile/ProfileBox.tsx
  src/components/profile/SkeletonProfileBox.tsx
  src/components/signup/CareerToggle.tsx
  src/components/signup/ExperienceItem.tsx
  src/components/signup/ExperienceSection.tsx
  src/components/signup/PositionSelect.tsx
  src/components/signup/Select.tsx
  src/store/authStore.ts
  src/stories/mypage/AddBtn.stories.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ FEAT, 🛠️ FIX

#33 fix: 내 정보 수정, 경력 삭제
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  src/components/common/NevBar.tsx
  src/components/mypage/Carousel.tsx
  src/components/mypage/Home.tsx
  src/components/mypage/MyExperienceSection.tsx
  src/components/mypage/Profile.tsx
  src/components/signup/ExperienceItem.tsx
  src/components/signup/ExperienceSection.tsx
  src/store/authStore.ts
Labels: 🛠️ FIX

#34 feat: 이벤트 조회, 생성 api 연동
  package.json
  public/whiteplus.png
  src/app/calendar/api/getEventList.ts
  src/app/calendar/api/postEvent.ts
  src/app/calendar/page.tsx
  src/components/calender/AddCalendarBtn.tsx
  src/components/calender/AddCalenderModal.tsx
  src/components/calender/Calendar.tsx
  src/components/calender/CalendarEventCard.tsx
  src/components/calender/CategoryBtn.tsx
  src/components/calender/FilterBtn.tsx
  src/constants/category.ts
  yarn.lock
Labels: ✨ FEAT

#36 feat: 이벤트 단일 조회, 수정, 삭제 연동
  public/XIcon.svg
  public/pencil.svg
  public/trashbin.svg
  src/app/calendar/api/deleteEvent.ts
  src/app/calendar/api/getEvent.ts
  src/app/calendar/api/patchEvent.ts
  src/app/calendar/api/postEvent.ts
  src/app/calendar/page.tsx
  src/components/calender/AddCalendarBtn.tsx
  src/components/calender/AddCalendarModal.tsx
  src/components/calender/Calendar.tsx
  src/components/calender/CalendarEventCard.tsx
  src/components/calender/EventDeleteModal.tsx
  src/components/calender/EventsDetailModal.tsx
  src/types/calendar.ts
Labels: ✨ FEAT

#40 feat : 기존의 alert를 북마크 성공, 취소 모달로 적용
  src/components/blog/BlogMenu.tsx
  src/components/blog/BlogPost.tsx
  src/components/common/BookmarkModal.tsx
  src/components/mypage/Bookmark.tsx
  src/components/mypage/Likes.tsx
  src/components/session/SessionMenu.tsx
  src/components/session/SessionPost.tsx
  src/components/session/ShowVideo.tsx
Labels: ✨ FEAT, 🛠️ FIX

#41 fix : 블로그, 세션 테스트 오류 수정
  src/app/profile/api/getProfileList.ts
  src/app/profile/api/getUserProfile.ts
  src/components/blog/AddPostModal.tsx
  src/components/common/ModalInputField.tsx
  src/components/onboarding/Fourth.tsx
  src/components/session/AddSessionModal.tsx
  src/components/session/EditSession.tsx
  src/components/session/ShowVideo.tsx
  src/stories/components/ModalInputField.stories.tsx
Labels: 🛠️ FIX

#43 fix : 탭바 수정사항 수정 및 탭바 페이지 이동 시 옵션[0] 초기화
  src/app/blog/page.tsx
  src/app/session/page.tsx
  src/components/common/TapBar.tsx
  src/components/mypage/Bookmark.tsx
  src/components/mypage/Likes.tsx
Labels: ✨ FEAT, 🛠️ FIX

#37 feat: 프로젝트 연동
  next.config.mjs
  public/images/project/github.svg
  public/images/project/notion.svg
  public/loading.json
  public/mockServiceWorker.js
  src/api/project/common.ts
  src/api/project/project/project.ts
  src/app/mypage/page.tsx
  src/app/project/add/project/@modal/(.)addMember/page.tsx
  src/app/project/add/project/@modal/default.tsx
  src/app/project/add/project/addMember/page.tsx
  src/app/project/add/project/layout.tsx
  src/app/project/add/project/page.tsx
  src/app/project/add/study/page.tsx
  src/app/project/detail/project/[id]/page.tsx
  src/app/project/detail/project/edit/[id]/page.tsx
  src/app/project/detail/study/[id]/page.tsx
  src/app/project/detail/study/edit/[id]/page.tsx
  src/app/project/page.tsx
  src/app/session/_lib/getBestSessions.ts
  src/components/common/Loading.tsx
  src/components/common/NevBar.tsx
  src/components/common/PositionTag.tsx
  src/components/mypage/Carousel.tsx
  src/components/mypage/Home.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/ProfileInputField.tsx
  src/components/project/ProjectCard.tsx
  src/components/project/add/AddMember.tsx
  src/components/project/add/AddProfile.tsx
  src/components/project/add/AddRecruit.tsx
  src/components/project/add/ExistingResultImgBox.tsx
  src/components/project/add/ResultImgBox.tsx
  src/components/project/add/project/AddResults.tsx
  src/components/project/add/project/AddStack.tsx
  src/components/project/add/project/StackDropdown.tsx
  src/components/project/detail/Applicants.tsx
  src/components/project/detail/FindMember.tsx
  src/components/project/detail/Member.tsx
  src/components/project/detail/Profile.tsx
  src/components/project/detail/Results.tsx
  src/components/project/detail/Stack.tsx
  src/components/project/modal/ApplicantModal.tsx
  src/components/project/modal/ApplyModal.tsx
  src/components/project/modal/BigMemberBox.tsx
  src/components/project/modal/Btn.tsx
  src/components/project/modal/ProjectModal.tsx
  src/components/project/modal/RecruitInput.tsx
  src/components/search/ProjectCard.tsx
  src/components/search/ProjectSection.tsx
  src/store/authStore.ts
  src/stories/project/Member.stories.tsx
  src/stories/project/Stack.stories.tsx
  src/stories/project/modal/MemberModal.stories.tsx
  src/styles/positionStyles.ts
  yarn.lock
Labels: ✨ FEAT, 🛠️ FIX

#44 feat :프로필 페이지 무한스크롤 구현
  src/app/profile/@profiletList.tsx
  src/app/profile/api/getProfileList.ts
Labels: ✨ FEAT

#46 fix: 통합검색 페이지 수정 및 이력서, 프로필 무한스크롤 구현
  next.config.mjs
  public/f.pdf
  public/fe.pdf
  src/app/mypage/page.tsx
  src/app/profile/@profiletList.tsx
  src/app/profile/[userId]/page.tsx
  src/app/profile/api/getProfileList.ts
  src/app/profile/page.tsx
  src/app/profile/query/useGetProfileQuery.ts
  src/app/resume/@resumeList.tsx
  src/app/resume/[resumeId]/page.tsx
  src/app/resume/api/getResumeList.ts
  src/app/resume/api/getUserResume.ts
  src/app/resume/api/postResume.ts
  src/app/resume/page.tsx
  src/app/search/final/page.tsx
  src/components/common/Footer.tsx
  src/components/common/NavBar.tsx
  src/components/mypage/AddResume.tsx
  src/components/mypage/Resume.tsx
  src/components/profile/ProfileCard.tsx
  src/components/resume/OtherResume.tsx
  src/components/resume/SkeletonResume.tsx
  src/components/search/BlogCard.tsx
  src/components/search/BlogSection.tsx
  src/components/search/CategoryTab.tsx
  src/components/search/ProjectCard.tsx
  src/components/search/ProjectSection.tsx
  src/components/search/ResumeFolder.tsx
  src/components/search/ResumeSection.tsx
  src/components/search/SessionSection.tsx
  src/components/search/StudyCard.tsx
Labels: 🛠️ FIX

#52 feat : 개별페이지 서치엔진 구현
  src/app/blog/page.tsx
  src/app/project/page.tsx
  src/app/resume/page.tsx
  src/app/session/page.tsx
  src/components/common/NavBar.tsx
  src/components/common/SearchBar.tsx
  src/components/common/TapBar.tsx
Labels: ✨ FEAT, 🛠️ FIX

#51 fix: 로그인 모달, 오류 수정
  src/api/project/common.ts
  src/app/calendar/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/leave/page.tsx
  src/app/mypage/page.tsx
  src/app/profile/@profiletList.tsx
  src/app/profile/[userId]/page.tsx
  src/app/project/add/project/page.tsx
  src/app/project/add/study/page.tsx
  src/app/project/detail/project/[id]/page.tsx
  src/app/project/detail/project/edit/[id]/page.tsx
  src/app/project/detail/study/[id]/page.tsx
  src/app/project/detail/study/edit/[id]/page.tsx
  src/app/project/page.tsx
  src/app/resume/[resumeId]/page.tsx
  src/app/session/_lib/getBestSessions.ts
  src/app/session/_lib/getSessions.ts
  src/app/session/_lib/useSessionsQuery.ts
  src/app/signup/page.tsx
  src/components/common/AuthModal.tsx
  src/components/common/EmailVerification.tsx
  src/components/common/Footer.tsx
  src/components/common/NavBar.tsx
  src/components/common/NevBar.tsx
  src/components/common/PositionTag.tsx
  src/components/mypage/Bookmark.tsx
  src/components/mypage/Home.tsx
  src/components/mypage/Likes.tsx
  src/components/mypage/Profile.tsx
  src/components/mypage/Resume.tsx
  src/components/mypage/Settings.tsx
  src/components/mypage/Skeleton.tsx
  src/components/profile/ProfileCard.tsx
  src/components/profile/SkeletonProfileBox.tsx
  src/components/project/SkeletonProjectCard.tsx
  src/components/project/add/AddBtn.tsx
  src/components/project/detail/ProjectDetailSkeleton.tsx
  src/components/resume/SkeletonResume.tsx
  src/store/authStore.ts
  src/styles/globals.css
Labels: 🛠️ FIX
